/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CodeItem: typeof import('./../components/CodeItem.vue')['default']
    CodeRawView: typeof import('./../components/CodeRawView.vue')['default']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElMain: typeof import('element-plus/es')['ElMain']
    Footer: typeof import('./../components/Footer.vue')['default']
    Header: typeof import('./../components/Header.vue')['default']
    ProItem: typeof import('./../components/ProItem.vue')['default']
    ProView: typeof import('./../components/proView.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./../components/SvgIcon/index.vue')['default']
  }
}
